In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
cases_month = pd.read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/main/data/2025/2025-06-24/cases_month.csv')
cases_year = pd.read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/main/data/2025/2025-06-24/cases_year.csv')

In [4]:
cases_month.head(10)

,region,country,iso3,year,month,measles_suspect,measles_clinical,measles_epi_linked,measles_lab_confirmed,measles_total,rubella_clinical,rubella_epi_linked,rubella_lab_confirmed,rubella_total,discarded
0,AFR,Algeria,DZA,2012,1,8.0,6.0,0.0,2.0,8.0,NaN,NaN,NaN,NaN,0.0
1,AFR,Algeria,DZA,2012,2,10.0,10.0,0.0,0.0,10.0,NaN,NaN,NaN,NaN,0.0
2,AFR,Algeria,DZA,2012,3,17.0,17.0,0.0,0.0,17.0,NaN,NaN,NaN,NaN,0.0
3,AFR,Algeria,DZA,2012,4,7.0,5.0,0.0,0.0,5.0,0.0,0.0,1.0,1.0,2.0
4,AFR,Algeria,DZA,2012,5,14.0,11.0,0.0,0.0,11.0,0.0,0.0,3.0,3.0,3.0
5,AFR,Algeria,DZA,2012,6,10.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0,8.0,10.0
6,AFR,Algeria,DZA,2012,7,1.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,1.0
7,AFR,Algeria,DZA,2012,10,1.0,1.0,0.0,0.0,1.0,NaN,NaN,NaN,NaN,0.0
8,AFR,Algeria,DZA,2012,11,3.0,3.0,0.0,0.0,3.0,NaN,NaN,NaN,NaN,0.0
9,AFR,Algeria,DZA,2012,12,5.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,5.0

In [5]:
cases_month.tail(10)

,region,country,iso3,year,month,measles_suspect,measles_clinical,measles_epi_linked,measles_lab_confirmed,measles_total,rubella_clinical,rubella_epi_linked,rubella_lab_confirmed,rubella_total,discarded
22770,WPR,Viet Nam,VNM,2024,5,155.0,6.0,21.0,54.0,81.0,3.0,0.0,0.0,3.0,74.0
22771,WPR,Viet Nam,VNM,2024,6,158.0,8.0,10.0,62.0,80.0,2.0,0.0,0.0,2.0,78.0
22772,WPR,Viet Nam,VNM,2024,7,161.0,15.0,18.0,87.0,120.0,NaN,NaN,NaN,NaN,41.0
22773,WPR,Viet Nam,VNM,2024,8,181.0,14.0,12.0,92.0,118.0,0.0,0.0,1.0,1.0,63.0
22774,WPR,Viet Nam,VNM,2024,9,304.0,15.0,20.0,196.0,231.0,NaN,NaN,NaN,NaN,73.0
22775,WPR,Viet Nam,VNM,2024,10,379.0,19.0,56.0,256.0,331.0,5.0,0.0,5.0,10.0,48.0
22776,WPR,Viet Nam,VNM,2024,11,584.0,37.0,125.0,347.0,509.0,0.0,0.0,1.0,1.0,75.0
22777,WPR,Viet Nam,VNM,2024,12,588.0,56.0,134.0,338.0,528.0,0.0,0.0,1.0,1.0,60.0
22778,WPR,Viet Nam,VNM,2025,1,156.0,7.0,0.0,124.0,131.0,NaN,NaN,NaN,NaN,25.0
22779,WPR,Viet Nam,VNM,2025,2,22.0,0.0,0.0,20.0,20.0,NaN,NaN,NaN,NaN,2.0

In [6]:
cases_month.describe()

,year,month,measles_suspect,measles_clinical,measles_epi_linked,measles_lab_confirmed,measles_total,rubella_clinical,rubella_epi_linked,rubella_lab_confirmed,rubella_total,discarded
count,22780.000000,22780.000000,22632.000000,22632.000000,22632.000000,22632.000000,22632.000000,7811.000000,7811.000000,7811.000000,7811.000000,22632.000000
mean,2018.253600,6.293547,235.265376,50.708687,38.939069,47.029251,136.677006,19.815901,4.344130,20.066317,44.226347,112.301653
std,3.815709,3.461782,1203.690535,408.194314,748.287331,275.099951,969.226508,283.628969,60.004873,145.382545,335.242009,524.224152
min,2012.000000,1.000000,0.000000,-204.000000,0.000000,0.000000,-195.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2015.000000,3.000000,4.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000
50%,2018.000000,6.000000,23.000000,0.000000,0.000000,1.000000,2.000000,0.000000,0.000000,3.000000,4.000000,14.000000
75%,2022.000000,9.000000,110.000000,2.000000,0.000000,14.000000,29.000000,0.000000,0.000000,11.000000,15.000000,60.000000
max,2025.000000,12.000000,68051.000000,12730.000000,67728.000000,9936.000000,67929.000000,10856.000000,2476.000000,7039.000000,10856.000000,16443.000000

In [7]:
cases_month.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22780 entries, 0 to 22779
Data columns (total 15 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   region                 22780 non-null  object
 1   country                22780 non-null  object
 2   iso3                   22780 non-null  object
 3   year                   22780 non-null  int64
 4   month                  22780 non-null  int64
 5   measles_suspect        22632 non-null  float64
 6   measles_clinical       22632 non-null  float64
 7   measles_epi_linked     22632 non-null  float64
 8   measles_lab_confirmed  22632 non-null  float64
 9   measles_total          22632 non-null  float64
 10  rubella_clinical       7811 non-null   float64
 11  rubella_epi_linked     7811 non-null   float64
 12  rubella_lab_confirmed  7811 non-null   float64
 13  rubella_total          7811 non-null   float64
 14  discarded              22632 non-null  float64
dtypes: float64(10), int64(2), object(3)
memory usage: 2.6+ MB

In [8]:
cases_month['measles_total'].max()

67929.0

In [9]:
cases_month.loc[cases_month['measles_total'].idxmax()]

region                          AFR
country                  Madagascar
iso3                            MDG
year                           2019
month                             2
measles_suspect             68051.0
measles_clinical               12.0
measles_epi_linked          67728.0
measles_lab_confirmed         189.0
measles_total               67929.0
rubella_clinical                NaN
rubella_epi_linked              NaN
rubella_lab_confirmed           NaN
rubella_total                   NaN
discarded                     122.0
Name: 3599, dtype: object

In [10]:
cases_month['rubella_total'].max()

10856.0

In [11]:
cases_month.loc[cases_month['rubella_total'].idxmax()]

region                       EUR
country                   Poland
iso3                         POL
year                        2013
month                          4
measles_suspect              NaN
measles_clinical             NaN
measles_epi_linked           NaN
measles_lab_confirmed        NaN
measles_total                NaN
rubella_clinical         10856.0
rubella_epi_linked           0.0
rubella_lab_confirmed        0.0
rubella_total            10856.0
discarded                    NaN
Name: 16413, dtype: object

In [12]:
cases_month['country'].unique()

array(['Algeria', 'Angola', 'Benin', 'Botswana', 'Burkina Faso',
       'Burundi', 'Cabo Verde', 'Cameroon', 'Central African Republic',
       'Chad', 'Comoros', 'Congo', "Côte d'Ivoire",
       'Democratic Republic of the Congo', 'Equatorial Guinea', 'Eritrea',
       'Eswatini', 'Ethiopia', 'Gabon', 'Gambia', 'Ghana', 'Guinea',
       'Guinea-Bissau', 'Kenya', 'Lesotho', 'Liberia', 'Madagascar',
       'Malawi', 'Mali', 'Mauritania', 'Mozambique', 'Namibia', 'Niger',
       'Nigeria', 'Rwanda', 'Sao Tome and Principe', 'Senegal',
       'Seychelles', 'Sierra Leone', 'South Africa', 'South Sudan',
       'Togo', 'Uganda', 'United Republic of Tanzania', 'Zambia',
       'Zimbabwe', 'Antigua and Barbuda', 'Argentina', 'Bahamas',
       'Barbados', 'Belize', 'Bolivia (Plurinational State of)', 'Brazil',
       'Canada', 'Chile', 'Colombia', 'Costa Rica', 'Cuba', 'Dominica',
       'Dominican Republic', 'Ecuador', 'El Salvador', 'Grenada',
       'Guatemala', 'Guyana', 'Haiti', 'Honduras', 'Jamaica', 'Mexico',
       'Nicaragua', 'Panama', 'Paraguay', 'Peru', 'Saint Kitts and Nevis',
       'Saint Lucia', 'Saint Vincent and the Grenadines', 'Suriname',
       'Trinidad and Tobago', 'United States of America', 'Uruguay',
       'Venezuela (Bolivarian Republic of)', 'Afghanistan', 'Bahrain',
       'Djibouti', 'Egypt', 'Iran (Islamic Republic of)', 'Iraq',
       'Jordan', 'Kuwait', 'Lebanon', 'Libya', 'Morocco', 'Oman',
       'Pakistan', 'Qatar', 'Saudi Arabia', 'Somalia', 'Sudan',
       'Syrian Arab Republic', 'Tunisia', 'United Arab Emirates', 'Yemen',
       'Albania', 'Andorra', 'Armenia', 'Austria', 'Azerbaijan',
       'Belarus', 'Belgium', 'Bosnia and Herzegovina', 'Bulgaria',
       'Croatia', 'Cyprus', 'Czechia', 'Denmark', 'Estonia', 'Finland',
       'France', 'Georgia', 'Germany', 'Greece', 'Hungary', 'Iceland',
       'Ireland', 'Israel', 'Italy', 'Kazakhstan', 'Kyrgyzstan', 'Latvia',
       'Lithuania', 'Luxembourg', 'Malta', 'Monaco', 'Montenegro',
       'Netherlands (Kingdom of the)', 'North Macedonia', 'Norway',
       'Poland', 'Portugal', 'Republic of Moldova', 'Romania',
       'Russian Federation', 'San Marino', 'Serbia', 'Slovakia',
       'Slovenia', 'Spain', 'Sweden', 'Switzerland', 'Tajikistan',
       'Türkiye', 'Turkmenistan', 'Ukraine',
       'United Kingdom of Great Britain and Northern Ireland',
       'Uzbekistan', 'Bangladesh', 'Bhutan',
       "Democratic People's Republic of Korea", 'India', 'Indonesia',
       'Maldives', 'Myanmar', 'Nepal', 'Sri Lanka', 'Thailand',
       'Timor-Leste', 'Australia', 'Brunei Darussalam', 'Cambodia',
       'China', 'Cook Islands', 'Fiji', 'Japan', 'Kiribati',
       "Lao People's Democratic Republic", 'Malaysia', 'Marshall Islands',
       'Micronesia (Federated States of)', 'Mongolia', 'Nauru',
       'New Zealand', 'Niue', 'Palau', 'Papua New Guinea', 'Philippines',
       'Republic of Korea', 'Samoa', 'Singapore', 'Solomon Islands',
       'Tonga', 'Tuvalu', 'Vanuatu', 'Viet Nam'], dtype=object)

In [13]:
cases_month['country'].nunique()

193

In [14]:
cases_month['region'].nunique()

6

In [15]:
cases_month.groupby(['region']).max()

,country,iso3,year,month,measles_suspect,measles_clinical,measles_epi_linked,measles_lab_confirmed,measles_total,rubella_clinical,rubella_epi_linked,rubella_lab_confirmed,rubella_total,discarded
region,,,,,,,,,,,,,,
AFR,Zimbabwe,ZWE,2025,12,68051.0,4278.0,67728.0,1173.0,67929.0,0.0,0.0,4207.0,4207.0,7486.0
AMR,Venezuela (Bolivarian Republic of),VEN,2025,12,19919.0,10.0,498.0,5928.0,5928.0,0.0,0.0,2.0,2.0,14260.0
EMR,Yemen,YEM,2025,12,9196.0,6916.0,1520.0,3873.0,8156.0,373.0,129.0,378.0,419.0,5304.0
EUR,Uzbekistan,UZB,2025,12,14006.0,12504.0,4509.0,9270.0,13760.0,10856.0,8.0,93.0,10856.0,2669.0
SEAR,Timor-Leste,TLS,2025,12,25758.0,12540.0,8184.0,6413.0,15177.0,0.0,2476.0,374.0,2476.0,10581.0
WPR,Viet Nam,WSM,2025,12,20321.0,12730.0,5195.0,9936.0,17228.0,9921.0,1157.0,7039.0,9921.0,16443.0

In [16]:
cases_region = cases_month['region'].unique()
cases_region

array(['AFR', 'AMR', 'EMR', 'EUR', 'SEAR', 'WPR'], dtype=object)

In [17]:
cases_month.columns

Index(['region', 'country', 'iso3', 'year', 'month', 'measles_suspect',
       'measles_clinical', 'measles_epi_linked', 'measles_lab_confirmed',
       'measles_total', 'rubella_clinical', 'rubella_epi_linked',
       'rubella_lab_confirmed', 'rubella_total', 'discarded'],
      dtype='object')

In [18]:
cols_of_interest = [
    'measles_suspect',
    'measles_clinical',
    'measles_epi_linked',
    'measles_lab_confirmed',
    'measles_total',
    'rubella_clinical',
    'rubella_epi_linked',
    'rubella_lab_confirmed',
    'rubella_total',
    'discarded'
]

regions = ['AFR', 'AMR', 'EMR', 'EUR', 'SEAR', 'WPR']

records = []

for region in regions:
    df_region = cases_month[cases_month['region'] == region]
    for col in cols_of_interest:
        idx = df_region[col].idxmax()
        row = df_region.loc[idx].copy()
        row['metric'] = col
        row['max_value'] = row[col]
        records.append(row)

region_max = pd.DataFrame(records)

region_max

,region,country,iso3,year,month,measles_suspect,measles_clinical,measles_epi_linked,measles_lab_confirmed,measles_total,rubella_clinical,rubella_epi_linked,rubella_lab_confirmed,rubella_total,discarded,metric,max_value
3599,AFR,Madagascar,MDG,2019,2,68051.0,12.0,67728.0,189.0,67929.0,NaN,NaN,NaN,NaN,122.0,measles_suspect,68051.0
4662,AFR,Nigeria,NGA,2022,2,7186.0,4278.0,301.0,962.0,5541.0,0.0,0.0,241.0,241.0,1645.0,measles_clinical,4278.0
3599,AFR,Madagascar,MDG,2019,2,68051.0,12.0,67728.0,189.0,67929.0,NaN,NaN,NaN,NaN,122.0,measles_epi_linked,67728.0
4663,AFR,Nigeria,NGA,2022,3,7128.0,3392.0,539.0,1173.0,5104.0,0.0,0.0,264.0,264.0,2024.0,measles_lab_confirmed,1173.0
3599,AFR,Madagascar,MDG,2019,2,68051.0,12.0,67728.0,189.0,67929.0,NaN,NaN,NaN,NaN,122.0,measles_total,67929.0
3,AFR,Algeria,DZA,2012,4,7.0,5.0,0.0,0.0,5.0,0.0,0.0,1.0,1.0,2.0,rubella_clinical,0.0
3,AFR,Algeria,DZA,2012,4,7.0,5.0,0.0,0.0,5.0,0.0,0.0,1.0,1.0,2.0,rubella_epi_linked,0.0
5319,AFR,South Africa,ZAF,2024,9,7771.0,43.0,0.0,242.0,285.0,0.0,0.0,4207.0,4207.0,7486.0,rubella_lab_confirmed,4207.0
5319,AFR,South Africa,ZAF,2024,9,7771.0,43.0,0.0,242.0,285.0,0.0,0.0,4207.0,4207.0,7486.0,rubella_total,4207.0
5319,AFR,South Africa,ZAF,2024,9,7771.0,43.0,0.0,242.0,285.0,0.0,0.0,4207.0,4207.0,7486.0,discarded,7486.0
6728,AMR,Brazil,BRA,2019,9,19919.0,0.0,0.0,5659.0,5659.0,NaN,NaN,NaN,NaN,14260.0,measles_suspect,19919.0
6306,AMR,Argentina,ARG,2019,10,534.0,10.0,1.0,15.0,26.0,NaN,NaN,NaN,NaN,508.0,measles_clinical,10.0
6889,AMR,Canada,CAN,2025,4,936.0,0.0,498.0,438.0,936.0,NaN,NaN,NaN,NaN,0.0,measles_epi_linked,498.0
6718,AMR,Brazil,BRA,2018,11,272.0,0.0,0.0,5928.0,5928.0,NaN,NaN,NaN,NaN,0.0,measles_lab_confirmed,5928.0
6718,AMR,Brazil,BRA,2018,11,272.0,0.0,0.0,5928.0,5928.0,NaN,NaN,NaN,NaN,0.0,measles_total,5928.0
6300,AMR,Argentina,ARG,2019,4,42.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,41.0,rubella_clinical,0.0
6300,AMR,Argentina,ARG,2019,4,42.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,41.0,rubella_epi_linked,0.0
6301,AMR,Argentina,ARG,2019,5,48.0,0.0,0.0,1.0,1.0,0.0,0.0,2.0,2.0,47.0,rubella_lab_confirmed,2.0
6301,AMR,Argentina,ARG,2019,5,48.0,0.0,0.0,1.0,1.0,0.0,0.0,2.0,2.0,47.0,rubella_total,2.0
6728,AMR,Brazil,BRA,2019,9,19919.0,0.0,0.0,5659.0,5659.0,NaN,NaN,NaN,NaN,14260.0,discarded,14260.0
11070,EMR,Pakistan,PAK,2024,5,9196.0,235.0,93.0,3633.0,3961.0,0.0,0.0,49.0,49.0,5235.0,measles_suspect,9196.0
10034,EMR,Iraq,IRQ,2024,2,8314.0,6916.0,910.0,330.0,8156.0,0.0,0.0,1.0,1.0,158.0,measles_clinical,6916.0
11670,EMR,Sudan,SDN,2023,7,1609.0,37.0,1520.0,16.0,1573.0,0.0,5.0,4.0,9.0,36.0,measles_epi_linked,1520.0
10934,EMR,Pakistan,PAK,2013,1,4655.0,0.0,0.0,3873.0,3873.0,0.0,0.0,141.0,141.0,782.0,measles_lab_confirmed,3873.0
10034,EMR,Iraq,IRQ,2024,2,8314.0,6916.0,910.0,330.0,8156.0,0.0,0.0,1.0,1.0,158.0,measles_total,8156.0
12276,EMR,Yemen,YEM,2021,2,1183.0,298.0,0.0,259.0,557.0,373.0,0.0,46.0,419.0,626.0,rubella_clinical,373.0
11665,EMR,Sudan,SDN,2023,2,555.0,25.0,175.0,108.0,308.0,0.0,129.0,36.0,165.0,247.0,rubella_epi_linked,129.0
11010,EMR,Pakistan,PAK,2019,5,1716.0,100.0,5.0,143.0,248.0,0.0,0.0,378.0,378.0,1468.0,rubella_lab_confirmed,378.0
12276,EMR,Yemen,YEM,2021,2,1183.0,298.0,0.0,259.0,557.0,373.0,0.0,46.0,419.0,626.0,rubella_total,419.0
11071,EMR,Pakistan,PAK,2024,6,8169.0,191.0,98.0,2576.0,2865.0,0.0,0.0,55.0,55.0,5304.0,discarded,5304.0
12977,EUR,Azerbaijan,AZE,2023,12,14006.0,5872.0,4509.0,956.0,11337.0,NaN,NaN,NaN,NaN,2669.0,measles_suspect,14006.0
18407,EUR,Ukraine,UKR,2019,1,0.0,12504.0,0.0,1256.0,13760.0,15.0,0.0,2.0,17.0,0.0,measles_clinical,12504.0
12977,EUR,Azerbaijan,AZE,2023,12,14006.0,5872.0,4509.0,956.0,11337.0,NaN,NaN,NaN,NaN,2669.0,measles_epi_linked,4509.0
15429,EUR,Kazakhstan,KAZ,2024,1,0.0,33.0,207.0,9270.0,9510.0,0.0,0.0,5.0,5.0,0.0,measles_lab_confirmed,9270.0
18407,EUR,Ukraine,UKR,2019,1,0.0,12504.0,0.0,1256.0,13760.0,15.0,0.0,2.0,17.0,0.0,measles_total,13760.0
16413,EUR,Poland,POL,2013,4,NaN,NaN,NaN,NaN,NaN,10856.0,0.0,0.0,10856.0,NaN,rubella_clinical,10856.0
18345,EUR,Ukraine,UKR,2013,7,0.0,74.0,0.0,73.0,147.0,1.0,8.0,0.0,9.0,0.0,rubella_epi_linked,8.0
17094,EUR,Russian Federation,RUS,2025,1,740.0,1.0,1.0,351.0,353.0,0.0,1.0,93.0,94.0,387.0,rubella_lab_confirmed,93.0
16413,EUR,Poland,POL,2013,4,NaN,NaN,NaN,NaN,NaN,10856.0,0.0,0.0,10856.0,NaN,rubella_total,10856.0
12977,EUR,Azerbaijan,AZE,2023,12,14006.0,5872.0,4509.0,956.0,11337.0,NaN,NaN,NaN,NaN,2669.0,discarded,2669.0
19280,SEAR,India,IND,2022,12,25758.0,1709.0,8184.0,5284.0,15177.0,0.0,27.0,374.0,401.0,10581.0,measles_suspect,25758.0
19199,SEAR,India,IND,2016,3,18104.0,12540.0,2038.0,0.0,14578.0,0.0,1227.0,0.0,1227.0,3526.0,measles_clinical,12540.0
19280,SEAR,India,IND,2022,12,25758.0,1709.0,8184.0,5284.0,15177.0,0.0,27.0,374.0,401.0,10581.0,measles_epi_linked,8184.0
19283,SEAR,India,IND,2023,3,20964.0,1329.0,4144.0,6413.0,11886.0,0.0,21.0,264.0,285.0,9078.0,measles_lab_confirmed,6413.0
19280,SEAR,India,IND,2022,12,25758.0,1709.0,8184.0,5284.0,15177.0,0.0,27.0,374.0,401.0,10581.0,measles_total,15177.0
18737,SEAR,Bangladesh,BGD,2012,1,590.0,1.0,310.0,102.0,413.0,0.0,83.0,10.0,93.0,177.0,rubella_clinical,0.0
19197,SEAR,India,IND,2016,1,15679.0,5844.0,4808.0,0.0,10652.0,0.0,2476.0,0.0,2476.0,5027.0,rubella_epi_linked,2476.0
19280,SEAR,India,IND,2022,12,25758.0,1709.0,8184.0,5284.0,15177.0,0.0,27.0,374.0,401.0,10581.0,rubella_lab_confirmed,374.0
19197,SEAR,India,IND,2016,1,15679.0,5844.0,4808.0,0.0,10652.0,0.0,2476.0,0.0,2476.0,5027.0,rubella_total,2476.0
19280,SEAR,India,IND,2022,12,25758.0,1709.0,8184.0,5284.0,15177.0,0.0,27.0,374.0,401.0,10581.0,discarded,10581.0
20805,WPR,China,CHN,2014,4,20321.0,534.0,0.0,9936.0,10470.0,2295.0,0.0,0.0,2295.0,9851.0,measles_suspect,20321.0
22176,WPR,Philippines,PHL,2019,2,15025.0,12730.0,601.0,1264.0,14595.0,0.0,1.0,24.0,25.0,430.0,measles_clinical,12730.0
22115,WPR,Philippines,PHL,2014,1,18823.0,7703.0,5195.0,4330.0,17228.0,0.0,0.0,88.0,88.0,1595.0,measles_epi_linked,5195.0
20805,WPR,China,CHN,2014,4,20321.0,534.0,0.0,9936.0,10470.0,2295.0,0.0,0.0,2295.0,9851.0,measles_lab_confirmed,9936.0
22115,WPR,Philippines,PHL,2014,1,18823.0,7703.0,5195.0,4330.0,17228.0,0.0,0.0,88.0,88.0,1595.0,measles_total,17228.0
20782,WPR,China,CHN,2012,5,5613.0,10.0,1.0,677.0,688.0,9921.0,0.0,0.0,9921.0,4925.0,rubella_clinical,9921.0
20866,WPR,China,CHN,2019,5,16948.0,24.0,0.0,481.0,505.0,666.0,1157.0,7039.0,8862.0,16443.0,rubella_epi_linked,1157.0
20866,WPR,China,CHN,2019,5,16948.0,24.0,0.0,481.0,505.0,666.0,1157.0,7039.0,8862.0,16443.0,rubella_lab_confirmed,7039.0
20782,WPR,China,CHN,2012,5,5613.0,10.0,1.0,677.0,688.0,9921.0,0.0,0.0,9921.0,4925.0,rubella_total,9921.0
20866,WPR,China,CHN,2019,5,16948.0,24.0,0.0,481.0,505.0,666.0,1157.0,7039.0,8862.0,16443.0,discarded,16443.0

In [19]:
region_max['country'].unique()

array(['Madagascar', 'Nigeria', 'Algeria', 'South Africa', 'Brazil',
       'Argentina', 'Canada', 'Pakistan', 'Iraq', 'Sudan', 'Yemen',
       'Azerbaijan', 'Ukraine', 'Kazakhstan', 'Poland',
       'Russian Federation', 'India', 'Bangladesh', 'China',
       'Philippines'], dtype=object)

In [20]:
region_max['year'].min()

2012

In [21]:
most_common_month = (
    region_max.groupby('region')['month'].agg(lambda x: x.value_counts().idxmax()).reset_index(name='most_common_month')
)
most_common_month

  region  most_common_month
0    AFR                  2
1    AMR                  4
2    EMR                  2
3    EUR                  1
4   SEAR                 12
5    WPR                  5

In [22]:
most_common_country = (
    region_max.groupby('region')['country'].agg(lambda x: x.value_counts().idxmax()).reset_index(name='most_common_country')
)
most_common_country

  region most_common_country
0    AFR          Madagascar
1    AMR           Argentina
2    EMR            Pakistan
3    EUR          Azerbaijan
4   SEAR               India
5    WPR               China

In [24]:
cases_month.groupby(['region']).describe(include='all')

       country                                                               \
         count unique                               top freq mean  std  min
region
AFR       6241     46  Democratic Republic of the Congo  161  NaN  NaN  NaN
AMR       2986     35                              Cuba  138  NaN  NaN  NaN
EMR       3101     21                          Pakistan  162  NaN  NaN  NaN
EUR       6409     53                       Switzerland  160  NaN  NaN  NaN
SEAR      1639     11                        Bangladesh  161  NaN  NaN  NaN
WPR       2404     27                             China  160  NaN  NaN  NaN

                       ... discarded                                         \
        25%  50%  75%  ...    unique top freq        mean          std  min
region                 ...
AFR     NaN  NaN  NaN  ...       NaN NaN  NaN   75.833841   195.975762  0.0
AMR     NaN  NaN  NaN  ...       NaN NaN  NaN   76.162090   406.728394  0.0
EMR     NaN  NaN  NaN  ...       NaN NaN  NaN  125.097065   284.339607  0.0
EUR     NaN  NaN  NaN  ...       NaN NaN  NaN   19.411210    97.033638  0.0
SEAR    NaN  NaN  NaN  ...       NaN NaN  NaN  354.364246  1157.051917  0.0
WPR     NaN  NaN  NaN  ...       NaN NaN  NaN  312.372035  1064.986155  0.0


         25%   50%    75%      max
region
AFR      8.0  25.0   78.0   7486.0
AMR      3.0  14.0   53.0  14260.0
EMR     13.0  41.0  122.0   5304.0
EUR      0.0   0.0    6.0   2669.0
SEAR     9.0  37.0  187.0  10581.0
WPR      3.0  20.0  111.0  16443.0

[6 rows x 154 columns]

In [ ]:
cases_month.rename(columns = {'a': 'b', 'c': 'd'})